# Generated by Django 5.2.4 on 2026-01-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0003_section_recolte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depense', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('legumineuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.legumineuse')),
            ],
        ),
    ]
