# Generated by Django 5.2.4 on 2026-01-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0003_section_recolte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('quantite', models.FloatField(help_text='Quantité commandée en kg')),
                ('date_commande', models.DateField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=50)),
                ('legumineuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.legumineuse')),
            ],
        ),
    ]
