# Generated by Django 5.2.4 on 2026-01-08 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande'], 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, help_text='Date de livraison prévue', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison_reelle',
            field=models.DateField(blank=True, help_text='Date de livraison réelle', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='notes_staff',
            field=models.TextField(blank=True, help_text='Notes internes pour le staff'),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_unitaire',
            field=models.FloatField(blank=True, help_text='Prix unitaire en FCFA', null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('En livraison', 'En livraison'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=50),
        ),
    ]
