# Generated by Django 5.2.4 on 2026-01-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_commande_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_client',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='email_client',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom_client',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='prenom_client',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_client',
            field=models.CharField(blank=True, help_text='Avec indicatif, ex: +229 ...', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_unitaire',
            field=models.FloatField(blank=True, help_text='Prix unitaire en FCFA', null=True),
        ),
    ]
