# Generated by Django 5.2.4 on 2026-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commande_adresse_client_commande_email_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='adresse_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='email_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='nom_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='prenom_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='telephone_client',
        ),
        migrations.AddField(
            model_name='commande',
            name='client_adresse',
            field=models.CharField(blank=True, help_text='Adresse de livraison du client', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_nom',
            field=models.CharField(blank=True, help_text='Nom du client au moment de la commande', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_telephone',
            field=models.CharField(blank=True, help_text='Téléphone du client', max_length=20, null=True),
        ),
    ]
