# Generated by Django 5.2.4 on 2026-01-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0003_section_recolte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.FloatField(help_text='Quantité en kg')),
                ('date_mise_a_jour', models.DateField(auto_now=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.legumineuse')),
            ],
        ),
    ]
