# Generated by Django 5.2.4 on 2026-01-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='culture',
            new_name='legumineuse',
        ),
    ]
