# Generated by Django 5.2.4 on 2026-02-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_culture_stock_legumineuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
