# Generated by Django 5.2.4 on 2026-02-25 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_remove_section_legumineuse'),
        ('stock', '0003_alter_stock_date_mise_a_jour'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.FloatField(help_text='Quantité en kg')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(help_text='Ex: Récolte, Vente, Ajustement manuel', max_length=255)),
                ('legumineuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.legumineuse')),
            ],
        ),
    ]
