# Generated by Django 5.2.4 on 2026-01-07 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0003_section_recolte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(help_text='Quantité vendue en kg')),
                ('prix_unitaire', models.FloatField(help_text='Prix par kg')),
                ('client', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('legumineuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.legumineuse')),
            ],
        ),
    ]
