# Generated by Django 5.2.4 on 2026-01-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_legumineuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(help_text='Quantité en kg')),
                ('date', models.DateField()),
                ('qualite', models.CharField(max_length=50)),
                ('legumineuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.legumineuse')),
            ],
        ),
    ]
