# Generated by Django 5.2.4 on 2026-01-08 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_section_recolte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legumineuse',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id_section']},
        ),
        migrations.AddField(
            model_name='legumineuse',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legumineuse',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legumineuses', to='production.section'),
        ),
        migrations.AddField(
            model_name='legumineuse',
            name='type_legumineuse',
            field=models.CharField(choices=[('soja', 'Soja'), ('haricot', 'Haricot'), ('arachide', 'Arachide'), ('niebe', 'Niébé')], default='soja', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='id_section',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='superficie',
            field=models.FloatField(help_text='Superficie en m²'),
        ),
    ]
