# Generated by Django 5.2.4 on 2026-01-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_legumineuse_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legumineuse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RemoveField(
            model_name='legumineuse',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='legumineuse',
            name='section',
        ),
        migrations.RemoveField(
            model_name='legumineuse',
            name='type_legumineuse',
        ),
        migrations.RemoveField(
            model_name='section',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id_section',
        ),
        migrations.AlterField(
            model_name='section',
            name='superficie',
            field=models.FloatField(),
        ),
    ]
