# Generated by Django 5.2.4 on 2026-01-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_legumineuse_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legumineuse',
            name='prix_unitaire',
            field=models.FloatField(blank=True, help_text='Prix unitaire en FCFA/kg', null=True),
        ),
    ]
