# Generated by Django 5.2.4 on 2026-01-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_legumineuse_prix_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legumineuse',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix unitaire en FCFA/kg', max_digits=12, null=True),
        ),
    ]
