# Generated by Django 5.2.4 on 2026-01-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_legumineuse_prix_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legumineuse',
            name='prix_unitaire',
            field=models.FloatField(blank=True, help_text='Prix unitaire en FCFA/kg', null=True),
        ),
    ]
