# Generated by Django 5.2.4 on 2026-01-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_legumineuse_prix_unitaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legumineuse',
            name='prix_unitaire',
        ),
    ]
