# Generated by Django 5.2.4 on 2026-01-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_legumineuse_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='legumineuse',
            name='prix_unitaire',
            field=models.FloatField(blank=True, help_text='Prix unitaire en FCFA', null=True),
        ),
    ]
