# Generated by Django 5.2.4 on 2026-01-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_employe_section_legumineuse_section_recolte_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='section',
        ),
        migrations.RemoveField(
            model_name='legumineuse',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='production.employe'),
        ),
        migrations.AddField(
            model_name='section',
            name='legumineuse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='production.legumineuse'),
        ),
        migrations.AlterField(
            model_name='recolte',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='production.section'),
        ),
    ]
