# Generated by Django 5.2.4 on 2026-01-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_remove_employe_section_remove_legumineuse_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='production.section'),
        ),
        migrations.AddField(
            model_name='legumineuse',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legumineuses_cultures', to='production.section'),
        ),
    ]
