# Generated by Django 5.2.4 on 2026-01-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_employe_section_legumineuse_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='legumineuse',
        ),
    ]
