# Generated by Django 5.2.4 on 2026-02-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.IntegerField(blank=True, help_text="ID de l'objet lié (Stock ou Commande)", null=True),
        ),
    ]
