# Generated by Django 5.2.4 on 2026-01-09 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0003_alter_commande_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('date_embauche', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_livraison', 'En livraison'), ('indisponible', 'Indisponible')], default='disponible', max_length=20)),
                ('vehicule', models.CharField(blank=True, help_text='Marque et modèle du véhicule', max_length=100)),
                ('immatriculation', models.CharField(blank=True, max_length=20, unique=True)),
                ('numero_contact_urgence', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Chauffeurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planifiee', models.DateTimeField()),
                ('date_livraison', models.DateTimeField(blank=True, help_text='Date/heure réelle de livraison', null=True)),
                ('adresse_livraison', models.TextField()),
                ('notes_livraison', models.TextField(blank=True, help_text='Notes du chauffeur sur la livraison')),
                ('statut', models.CharField(choices=[('planifiée', 'Planifiée'), ('en_cours', 'En cours'), ('livrée', 'Livrée'), ('échouée', 'Échouée'), ('annulée', 'Annulée')], default='planifiée', max_length=20)),
                ('signature_client', models.TextField(blank=True, help_text='Données de signature en base64')),
                ('photo_preuve', models.ImageField(blank=True, null=True, upload_to='livraisons_photos/')),
                ('temperature', models.FloatField(blank=True, help_text='Température du produit à la livraison', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='livraisons.chauffeur')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
            ],
            options={
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='livraisons.livraison')),
            ],
            options={
                'verbose_name_plural': 'Historiques de livraison',
                'ordering': ['-date_modification'],
            },
        ),
    ]
